server:
    port: 8130 # 服务端口
spring:
    profiles:
        active: dev # 环境设置
    application:
        name: service-job # 服务名

#spring:
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848 # nacos服务地址
    main:
        allow-bean-definition-overriding: true


feign:
    client:
        config:
            default:
                connectTimeout: 10000 #连接超时配置
                readTimeout: 600000 #执行超时配置
#开启Feign对Sentinel的支持
#feign:
    sentinel:
        enabled: true

logging:
    level:
        com.xiyo.pfund.consume: DEBUG #以什么级别监控哪个接口



